CREATE TABLE [__MigrationHistory] (
  [MigrationId] nvarchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  [ContextKey] nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  [Model] varbinary(max)  NOT NULL,
  [ProductVersion] nvarchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED ([MigrationId], [ContextKey])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [__MigrationHistory] SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE [AspNetRoles] (
  [Id] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  [Name] nvarchar(256) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK_dbo.AspNetRoles] PRIMARY KEY CLUSTERED ([Id])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [AspNetRoles] SET (LOCK_ESCALATION = TABLE)
GO
CREATE UNIQUE NONCLUSTERED INDEX [RoleNameIndex]
ON [].[AspNetRoles] (
  [Name] ASC
)
GO

CREATE TABLE [AspNetUserClaims] (
  [Id] int  IDENTITY(1,1) NOT NULL,
  [UserId] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  [ClaimType] nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [ClaimValue] nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  CONSTRAINT [PK_dbo.AspNetUserClaims] PRIMARY KEY CLUSTERED ([Id])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [AspNetUserClaims] SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE [AspNetUserLogins] (
  [LoginProvider] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  [ProviderKey] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  [UserId] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK_dbo.AspNetUserLogins] PRIMARY KEY CLUSTERED ([LoginProvider], [ProviderKey], [UserId])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [AspNetUserLogins] SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE [AspNetUserRoles] (
  [UserId] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  [RoleId] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK_dbo.AspNetUserRoles] PRIMARY KEY CLUSTERED ([UserId], [RoleId])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [AspNetUserRoles] SET (LOCK_ESCALATION = TABLE)
GO
CREATE NONCLUSTERED INDEX [IX_UserId]
ON [].[AspNetUserRoles] (
  [UserId] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_RoleId]
ON [].[AspNetUserRoles] (
  [RoleId] ASC
)
GO

CREATE TABLE [AspNetUsers] (
  [Id] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  [Email] nvarchar(256) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [EmailConfirmed] bit  NOT NULL,
  [PasswordHash] nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [SecurityStamp] nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [PhoneNumber] nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [PhoneNumberConfirmed] bit  NOT NULL,
  [TwoFactorEnabled] bit  NOT NULL,
  [LockoutEndDateUtc] datetime  NULL,
  [LockoutEnabled] bit  NOT NULL,
  [AccessFailedCount] int  NOT NULL,
  [UserName] nvarchar(256) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED ([Id])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [AspNetUsers] SET (LOCK_ESCALATION = TABLE)
GO
CREATE UNIQUE NONCLUSTERED INDEX [UserNameIndex]
ON [].[AspNetUsers] (
  [UserName] ASC
)
GO

CREATE TABLE [BOT] (
  [id_peticion] int  IDENTITY(1,1) NOT NULL,
  [id_pregunta] int  NOT NULL,
  [id_respuesta] int  NOT NULL,
  [id_usuario] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK_PETICION_USUARIO] PRIMARY KEY CLUSTERED ([id_peticion])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [BOT] SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE [BotPreguntas] (
  [id_pregunta] int  IDENTITY(1,1) NOT NULL,
  [pregunta] text COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK_BotPreguntas] PRIMARY KEY CLUSTERED ([id_pregunta])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [BotPreguntas] SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE [BotRespuestas] (
  [id_respuesta] int  IDENTITY(1,1) NOT NULL,
  [respuesta] text COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK_BotRespuestas] PRIMARY KEY CLUSTERED ([id_respuesta])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [BotRespuestas] SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE [Cuenta] (
  [id_cuenta] int  IDENTITY(1,1) NOT NULL,
  [UserId] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK_Cuenta] PRIMARY KEY CLUSTERED ([id_cuenta])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [Cuenta] SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE [Dinero] (
  [id_Dinero] int  IDENTITY(1,1) NOT NULL,
  [Denominacion] int  NOT NULL,
  [Cantidad] int  NOT NULL,
  [id_Cuenta] int  NOT NULL,
  CONSTRAINT [PK_Dinero] PRIMARY KEY CLUSTERED ([id_Dinero])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [Dinero] SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE [LOG_ACCIONES] (
  [id_accion] int  IDENTITY(1,1) NOT NULL,
  [accion] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  [fecha] date  NOT NULL,
  [hora] time(7)  NOT NULL,
  [UserId] nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
  CONSTRAINT [PK__LOG_ACCI__387C4561AF10499A] PRIMARY KEY CLUSTERED ([id_accion])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
ALTER TABLE [LOG_ACCIONES] SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE [AspNetUserClaims] ADD CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE ON UPDATE NO ACTION
GO
ALTER TABLE [AspNetUserLogins] ADD CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE ON UPDATE NO ACTION
GO
ALTER TABLE [AspNetUserRoles] ADD CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [AspNetRoles] ([Id]) ON DELETE CASCADE ON UPDATE NO ACTION
GO
ALTER TABLE [AspNetUserRoles] ADD CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE ON UPDATE NO ACTION
GO
ALTER TABLE [BOT] ADD CONSTRAINT [FK_BOT_AspNetUsers] FOREIGN KEY ([id_usuario]) REFERENCES [AspNetUsers] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [BOT] ADD CONSTRAINT [FK_BOT_BotPreguntas] FOREIGN KEY ([id_pregunta]) REFERENCES [BotPreguntas] ([id_pregunta]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [BOT] ADD CONSTRAINT [FK_BOT_BotRespuestas] FOREIGN KEY ([id_respuesta]) REFERENCES [BotRespuestas] ([id_respuesta]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [Cuenta] ADD CONSTRAINT [FK_Cuenta_AspNetUsers] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE ON UPDATE NO ACTION
GO
ALTER TABLE [Dinero] ADD CONSTRAINT [FK_Dinero_Cuenta] FOREIGN KEY ([id_Cuenta]) REFERENCES [Cuenta] ([id_cuenta]) ON DELETE CASCADE ON UPDATE NO ACTION
GO
ALTER TABLE [LOG_ACCIONES] ADD CONSTRAINT [FK_LOG_ACCIONES_AspNetUsers] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE ON UPDATE NO ACTION
GO

